Repository otavanopisto/muikku, pull requests merged in 2023-09, with the labels that each got.

#6653 * Fixes for the sluggish material editor
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/context/readspeaker-context.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/workspace/progressData.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/workspace/workspaceMaterials/materials/index.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/workspace/workspaceMaterials/materials/material.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/containers/workspace.tsx
Labels: NEEDS REVIEW

#6654 ** Fix for couple of tests
  muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/AbstractUITest.java
  muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/guider/GuiderTestsBase.java
  muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/tor/ToRTestsBase.java
Labels: NEEDS REVIEW

#6657 6643 communicator openapi generator rework
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/actions/announcements/helpers.ts
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/actions/main-function/messages/helpers.ts
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/actions/main-function/messages/index.ts
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/api/api.ts
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/communicator/body/application/message-view.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/communicator/body/application/message-view/message.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/communicator/body/application/messages.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/communicator/body/application/toolbar.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/communicator/body/aside.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/communicator/dialogs/label-update.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/index/body/latest-messages-panel.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/reducers/index.ts
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/reducers/main-function/messages.ts
  muikku-core-plugins/src/main/resources/META-INF/resources/swagger.yaml
Labels: NEEDS REVIEW

#6663 GitHub actions update
  .github/workflows/accessibilityChecks.yml
  .github/workflows/announcerTest.yml
  .github/workflows/announcerTestSauce.yml
  .github/workflows/communicatorTest.yml
  .github/workflows/communicatorTestSauce.yml
  .github/workflows/courseAnnouncerTest.yml
  .github/workflows/courseAnnouncerTestSauce.yml
  .github/workflows/courseJournalTest.yml
  .github/workflows/courseJournalTestSauce.yml
  .github/workflows/courseManagementTest.yml
  .github/workflows/courseManagementTestSauce.yml
  .github/workflows/courseMaterialsManagementTest.yml
  .github/workflows/courseMaterialsManagementTestSauce.yml
  .github/workflows/courseMaterialsTest.yml
  .github/workflows/courseMaterialsTestSauce.yml
  .github/workflows/courseMaterialsTestSauceEdge.yml
  .github/workflows/courseMaterialsTestSauceFirefox.yml
  .github/workflows/courseMaterialsTestSauceSafari.yml
  .github/workflows/coursePickerTestSauce.yml
  .github/workflows/courseTestSauce.yml
  .github/workflows/courseTests.yml
  .github/workflows/courseUsersTest.yml
  .github/workflows/courseUsersTestSauce.yml
  .github/workflows/coursepickerTests.yml
  .github/workflows/deploySnapshot.yml
  .github/workflows/discussionsTest.yml
  .github/workflows/discussionsTestSauce.yml
  .github/workflows/flagTestSauce.yml
  .github/workflows/flagsTest.yml
  .github/workflows/guiderTest.yml
  .github/workflows/guiderTestSauce.yml
  .github/workflows/indexPageTest.yml
  .github/workflows/indexPageTestSauce.yml
  .github/workflows/newevaluationTest.yml
  .github/workflows/newevaluationTestSauce.yml
  .github/workflows/releaseOrDeploy.yml
  .github/workflows/restTest.yml
  .github/workflows/torTest.yml
  .github/workflows/torTestSauce.yml
  .github/workflows/userTest.yml
  .github/workflows/userTestSauce.yml
Labels: NEEDS REVIEW

#6662 Enviromental level announcement are not anymore loaded in workspace
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/actions/announcements/index.ts
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/containers/main-function.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/containers/workspace.tsx
Labels: NEEDS REVIEW

#6670 Logged in status fix which prevented staff and announcmenets loading …
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/actions/base/status.ts
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/actions/index.ts
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/reducers/base/status.ts
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/run/index.ts
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/util/base-main-function.ts
Labels: NEEDS REVIEW

#6669 Corrected guider link in course signup
  muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/coursepicker/CoursePickerRESTService.java
Labels: NEEDS REVIEW

#6626 3837 lock topics in discussions
  muikku-atests-plugin-rest-model/src/main/java/fi/otavanopisto/muikku/atests/DiscussionThread.java
  muikku-atests-plugin-rest-model/src/main/java/fi/otavanopisto/muikku/atests/LockForumThread.java
  muikku-atests-plugin/src/main/java/fi/otavanopisto/muikku/atests/AcceptanceTestsRESTService.java
  muikku-atests/src/test/java/fi/otavanopisto/muikku/rest/test/plugins/forum/ForumMessagePermissionsTestsIT.java
  muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/AbstractUITest.java
  muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/discussions/DiscussionTestsBase.java
  muikku-core-plugins-persistence/src/main/java/fi/otavanopisto/muikku/plugins/forum/model/ForumThread.java
  muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/forum/ForumController.java
  muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/forum/dao/ForumThreadDAO.java
  muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/forum/rest/ForumRESTModels.java
  muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/forum/rest/ForumRESTService.java
  muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/forum/rest/LockPayload.java
  muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/forum/rest/WorkspaceForumRESTService.java
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/actions/discussion/index.ts
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/discussion/body/application/discussion-current-thread.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/discussion/body/application/discussion-subscriptions.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/discussion/body/application/discussion-thread-reply.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/discussion/body/application/discussion-threads.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/discussion/body/application/modify-thread-drawer.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/discussion/dialogs/modify-thread.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/discussion/dialogs/new-thread.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/workspace/workspaceDiscussions/index.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/reducers/discussion/index.ts
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/application-list.scss
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/environment-dialog.scss
  muikku-forum-plugin-rest-model/src/main/java/fi/otavanopisto/muikku/plugins/forum/rest/ForumThreadRESTModel.java
  muikku-persistence/src/main/java/fi/otavanopisto/muikku/model/forum/LockForumThread.java
  updates/1.138/230703_forumthread_lock.xml
Labels: NEEDS REVIEW

#6693 6685 read speaker message lokalisointi
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-loader/fields/audio-field/index.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-loader/fields/connect-field.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-loader/fields/file-field/index.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-loader/fields/journal-field.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-loader/fields/math-field.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-loader/fields/memo-field.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-loader/fields/multiselect-field.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-loader/fields/organizer-field.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-loader/fields/select-field.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-loader/fields/sorter-field.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-loader/fields/text-field.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-loader/static/iframe.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-loader/static/image.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-loader/static/mathjax.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-loader/static/strmathjax.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/locales/translations/en.json
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/locales/translations/fi.json
Labels: NEEDS REVIEW

#6700 Workspace tutor and organizer support
  muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/communicator/CommunicatorTestsBase.java
  muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/guider/GuiderTestsBase.java
  muikku-persistence/src/main/java/fi/otavanopisto/muikku/model/workspace/WorkspaceRoleArchetype.java
  muikku-school-data-pyramus/src/main/java/fi/otavanopisto/muikku/plugins/schooldatapyramus/PyramusIdentifierMapper.java
  updates/1.139/230925-workspace-roles.xml
Labels: NEEDS REVIEW

#6701 Fixed capitalization of table names for case-sensitive databases
  updates/1.138/230703_forumthread_lock.xml
Labels: NEEDS REVIEW

#6656 Role refactoring preparation
  muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/announcer/rest/AnnouncerRESTService.java
  muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/chat/ChatController.java
  muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/chat/ChatRESTService.java
  muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/chat/ChatSyncController.java
  muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/communicator/CommunicatorController.java
  muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/communicator/rest/CommunicatorRESTService.java
  muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/communicator/rest/CommunicatorRecipientsRESTService.java
  muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/forum/ForumController.java
  muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/guider/GuiderRESTService.java
  muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/hops/HopsController.java
  muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/hops/rest/HopsRestService.java
  muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/me/MeRESTService.java
  muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/notes/NotesRESTService.java
  muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/organizationmanagement/rest/OrganizationManagementWorkspaceRESTService.java
  muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/pedagogy/rest/PedagogyRestService.java
  muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/transcriptofrecords/rest/TranscriptofRecordsRESTService.java
  muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/user/rest/UserEntityFileRESTService.java
  muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/worklist/WorklistController.java
  muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/WorkspaceMaterialsBackingBean.java
  muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/rest/WorkspaceRESTService.java
  muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/rest/WorkspaceSystemRESTService.java
  muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspacenotes/rest/WorkspaceNoteRESTService.java
  muikku-core/src/main/java/fi/otavanopisto/muikku/security/impl/DefaultPermissionResolver.java
  muikku-core/src/main/java/fi/otavanopisto/muikku/session/AbstractSessionController.java
  muikku-core/src/main/java/fi/otavanopisto/muikku/session/SessionController.java
  muikku-core/src/main/java/fi/otavanopisto/muikku/session/SessionControllerDelegateImpl.java
  muikku-core/src/main/java/fi/otavanopisto/muikku/users/OrganizationEntityController.java
  muikku-core/src/main/java/fi/otavanopisto/muikku/users/UserEntityController.java
  muikku-core/src/main/java/fi/otavanopisto/muikku/users/UserSchoolDataIdentifierController.java
  muikku-persistence/src/main/java/fi/otavanopisto/muikku/model/users/UserSchoolDataIdentifier.java
  muikku-rest/src/main/java/fi/otavanopisto/muikku/rest/user/UserRESTService.java
Labels: NEEDS REVIEW

#6706 fixes a locale bug
  muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/tor/ToRTestsBase.java
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/guider/dialogs/student/tabs/state-of-studies.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/profile/body/application/general-information.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/records/body/application/summary.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/locales/translations/en.json
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/locales/translations/fi.json
Labels: NEEDS REVIEW

#6658 6647 coursepicker openapi generator rework
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/actions/base/status.ts
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/actions/main-function/guider/index.ts
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/actions/workspaces/helpers.ts
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/actions/workspaces/index.ts
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/actions/workspaces/organization.ts
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/input-contacts-autofill.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/coursepicker/body/application/courses.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/coursepicker/body/application/courses/course.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/coursepicker/body/aside.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/carousel/hooks/use-can-signup.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/graph/main-chart.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/pedagogical-support-form/hooks/useWorkspaces.ts
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/guider/body/aside.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/index/body/studies-panel.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/index/body/workspaces-panel.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/organization/body/application/workspaces.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/organization/body/application/workspaces/aside.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/workspace/workspaceHome/header.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/reducers/main-function/guider/index.ts
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/reducers/main-function/records/index.ts
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/reducers/main-function/records/summary.ts
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/reducers/workspaces/index.ts
  muikku-core-plugins/src/main/resources/META-INF/resources/swagger.yaml
Labels: NEEDS REVIEW, openapi

#6681 Discussion api rework done.
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/actions/base/status.ts
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/actions/discussion/index.ts
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/api/api.ts
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/discussion/body/application.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/discussion/body/application/discussion-current-thread.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/discussion/body/application/discussion-subscriptions.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/discussion/body/application/discussion-thread-reply.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/discussion/body/application/discussion-threads.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/discussion/body/application/modify-reply-thread-drawer.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/discussion/body/application/modify-thread-drawer.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/discussion/body/application/reply-thread-drawer.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/discussion/body/application/toolbar.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/discussion/dialogs/delete-area.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/discussion/dialogs/delete-thread-component.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/discussion/dialogs/modify-area.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/discussion/dialogs/modify-thread-reply.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/discussion/dialogs/modify-thread.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/discussion/dialogs/new-thread.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/discussion/dialogs/reply-thread.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/containers/main-function.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/containers/workspace.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/reducers/discussion/index.ts
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/reducers/index.ts
  muikku-core-plugins/src/main/resources/META-INF/resources/swagger.yaml
Labels: NEEDS REVIEW

#6689 Support for paid course assessments
  muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/newevaluation/NewEvaluationTestsBase.java
  muikku-core-plugins-persistence/src/main/java/fi/otavanopisto/muikku/plugins/ceepos/model/CeeposAssessmentRequestOrder.java
  muikku-core-plugins-persistence/src/main/java/fi/otavanopisto/muikku/plugins/ceepos/model/CeeposProductType.java
  muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/assessmentrequest/rest/AssessmentRequestRESTService.java
  muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/ceepos/CeeposController.java
  muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/ceepos/CeeposPayViewBackingBean.java
  muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/ceepos/dao/CeeposAssessmentRequestOrderDAO.java
  muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/ceepos/dao/CeeposProductDAO.java
  muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/ceepos/rest/CeeposRESTService.java
  muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/ceepos/rest/CeeposRedirectRestModel.java
  muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/ceepos/rest/CeeposReturnLinkRestModel.java
  muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/communicator/CommunicatorAssessmentRequestController.java
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/workspace/evaluation-request-dialog.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/ceepos/done.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/ceepos/pay.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/guider/dialogs/student/tabs/state-of-studies.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/locales/i18n.ts
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/locales/translations/en.json
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/locales/translations/fi.json
  muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/ceepos/CeeposJsPluginMessages_en.properties
  muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/ceepos/CeeposJsPluginMessages_fi.properties
  muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/ceepos/CeeposPluginMessages_en.properties
  muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/ceepos/CeeposPluginMessages_fi.properties
  muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/communicator/CommunicatorPluginMessages_fi.properties
  muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/workspace/WorkspaceJsPluginMessages_en.properties
  muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/workspace/WorkspaceJsPluginMessages_fi.properties
  muikku-core/src/main/java/fi/otavanopisto/muikku/schooldata/WorkspaceSchoolDataBridge.java
  muikku-core/src/main/java/fi/otavanopisto/muikku/schooldata/WorkspaceSchoolDataController.java
  muikku-core/src/main/java/fi/otavanopisto/muikku/schooldata/entity/WorkspaceAssessmentPrice.java
  muikku-rest/src/main/java/fi/otavanopisto/muikku/rest/model/Student.java
  muikku-school-data-pyramus/src/main/java/fi/otavanopisto/muikku/plugins/schooldatapyramus/PyramusGradingSchoolDataBridge.java
  muikku-school-data-pyramus/src/main/java/fi/otavanopisto/muikku/plugins/schooldatapyramus/PyramusWorkspaceSchoolDataBridge.java
  muikku-school-data-pyramus/src/main/java/fi/otavanopisto/muikku/plugins/schooldatapyramus/entities/PyramusSchoolDataEntityFactory.java
  muikku-school-data-pyramus/src/main/java/fi/otavanopisto/muikku/plugins/schooldatapyramus/entities/PyramusWorkspaceAssessmentPrice.java
  updates/1.140/230906-ceepos-assessments.xml
Labels: IN PROGRESS

#6683 Workspace journal api path rework done
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/@types/evaluation.ts
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/@types/journal.ts
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/actions/main-function/evaluation/evaluationActions.ts
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/actions/workspaces/helpers.ts
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/actions/workspaces/journals.ts
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/api/api.ts
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/evaluation/body/application/evaluation/editors/journal-comment-editor.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/evaluation/body/application/evaluation/evaluation-journal-event-comment.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/evaluation/body/application/evaluation/evaluation-journal-event-list.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/evaluation/body/application/evaluation/evaluation-journal-event.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/evaluation/dialogs/delete-journal-comment.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/records/body/application/assignments-and-diaries/hooks/useJournalComments.ts
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/records/body/application/assignments-and-diaries/hooks/useJournals.ts
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/records/body/application/current-record/journal.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/records/body/application/current-record/journalComment.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/workspace/workspaceJournal/body/application/editors/workspace-journal-comment-editor.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/workspace/workspaceJournal/body/application/workspace-journal-comment-list-item.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/workspace/workspaceJournal/dialogs/delete-journal-comment.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/reducers/main-function/evaluation/index.ts
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/reducers/main-function/records/index.ts
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/reducers/workspaces/index.ts
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/reducers/workspaces/journals.ts
  muikku-core-plugins/src/main/resources/META-INF/resources/swagger.yaml
Labels: NEEDS REVIEW

#6716 * isCourseMember now functions correctly
  muikku-core-plugins/src/main/resources/META-INF/resources/swagger.yaml
Labels: NEEDS REVIEW

#6710 6709 worklist openapi generator rework
  muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/worklist/rest/WorklistRESTService.java
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/@types/evaluation.ts
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/actions/main-function/evaluation/evaluationActions.ts
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/actions/main-function/profile.ts
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/evaluation/body/application/evaluation/editors/workspace-editor.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/profile/body/application/components/work-list-editable.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/profile/body/application/components/work-list-row.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/profile/body/application/components/work-list-section.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/profile/body/application/work-list.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/profile/dialogs/delete-worklist-item.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/profile/dialogs/submit-worklist-items.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/reducers/main-function/profile.ts
  muikku-core-plugins/src/main/resources/META-INF/resources/swagger.yaml
Labels: NEEDS REVIEW

#6720 Pedagogisen tuen suunnitelman näkyvyys
  muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/pedagogy/rest/PedagogyRestService.java
Labels: NEEDS REVIEW

#6712 6711 workspace notes openapi generator rework
  muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspacenotes/rest/WorkspaceNoteRESTService.java
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/actions/notebook/notebook.ts
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/note-book/note-book.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/note-book/note-editor.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/note-book/note-list.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/note-book/notebook-pdf-dialog.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/note-book/notebook-pdf.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/reducers/notebook/notebook.ts
  muikku-core-plugins/src/main/resources/META-INF/resources/swagger.yaml
Labels: NEEDS REVIEW

#6721 Save last modification when deleting forum messages and threads
  muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/forum/ForumController.java
  muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/forum/dao/ForumMessageDAO.java
  muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/forum/dao/ForumThreadReplyDAO.java
Labels: NEEDS REVIEW

#6722 6714 other minor m api path openapi generator rework
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/actions/base/contacts.ts
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/actions/base/credentials.ts
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/actions/base/locales.ts
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/forgot-password-dialog.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/chat/chat.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/credentials/body.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/credentials/body/return-credentials.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/records/body/application/summary.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/reducers/base/contacts.ts
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/reducers/base/credentials.ts
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/reducers/base/locales.ts
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/reducers/index.ts
  muikku-core-plugins/src/main/resources/META-INF/resources/swagger.yaml
Labels: NEEDS REVIEW
