Repository otavanopisto/muikku, pull requests merged in 2023-10, with the labels that each got.

#6726 Interim evaluation fixes
  muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/evaluation/EvaluationRESTService.java
Labels: NEEDS REVIEW

#6708 6695 coursepicker filters v1
  muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/coursepicker/CoursePickerController.java
  muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/coursepicker/CoursePickerRESTService.java
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/actions/workspaces/index.ts
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/actions/workspaces/organization.ts
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/coursepicker/body/aside.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/organization/body/application/workspaces/aside.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/reducers/workspaces/index.ts
  muikku-core-plugins/src/main/resources/META-INF/resources/swagger.yaml
  muikku-core/src/main/java/fi/otavanopisto/muikku/search/SearchProvider.java
  muikku-core/src/main/java/fi/otavanopisto/muikku/search/WorkspaceSearchBuilder.java
  muikku-elastic-search/src/main/java/fi/otavanopisto/muikku/plugins/search/ElasticSearchProvider.java
  muikku-elastic-search/src/main/java/fi/otavanopisto/muikku/plugins/search/ElasticWorkspaceSearchBuilder.java
Labels: NEEDS REVIEW

#6677 Evaluation api rework done. Needs testing
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/@types/evaluation.ts
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/actions/main-function/evaluation/evaluationActions.ts
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/actions/main-function/records/summary.ts
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/actions/workspaces/index.ts
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/actions/workspaces/journals.ts
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/api/api.ts
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-loader/external-content/interim-evaluation-editor.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/evaluation/body/application.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/evaluation/body/application/evaluation-list/evaluation-card.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/evaluation/body/application/evaluation-list/evaluations-list.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/evaluation/body/application/evaluation/editors/assignment-editor.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/evaluation/body/application/evaluation/editors/exercise-editor.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/evaluation/body/application/evaluation/editors/interim-evaluation-editor.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/evaluation/body/application/evaluation/editors/journal-feedback-editor.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/evaluation/body/application/evaluation/editors/supplementation-editor.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/evaluation/body/application/evaluation/editors/workspace-editor.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/evaluation/body/application/evaluation/evaluation-assessment-assignment.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/evaluation/body/application/evaluation/evaluation-assessment-intermin-evaluation.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/evaluation/body/application/evaluation/evaluation-assessment-list.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/evaluation/body/application/evaluation/evaluation-event-content-card.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/evaluation/body/application/evaluation/evaluation-journal-event-list.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/evaluation/body/application/evaluation/evaluation.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/evaluation/body/aside.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/evaluation/dialogs/archive.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/evaluation/dialogs/delete-journal-feedback.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/evaluation/dialogs/delete-request.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/evaluation/dialogs/delete.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/evaluation/dialogs/evaluate.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/guider/dialogs/student/workspaces/workspace.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/records/body/application/assignments-and-diaries/hooks/useJournals.ts
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/workspace/progressData.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/reducers/main-function/evaluation/index.ts
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/reducers/workspaces/index.ts
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/reducers/workspaces/journals.ts
  muikku-core-plugins/src/main/resources/META-INF/resources/swagger.yaml
Labels: NEEDS REVIEW

#6595 Materials are disabled if there is any type pending request ongoing
  muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/guider/GuiderTestsBase.java
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/ckeditor-loader/base/index.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/ckeditor-loader/static/mathjax-react-loader/index.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/ckeditor-loader/static/mathjax-react-loader/mathjax-collector.ts
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/ckeditor-loader/static/mathjax.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/workspace/workspaceMaterials/materials/material.tsx
Labels: NEEDS REVIEW

#6676 Guider path rework done.
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/actions/main-function/guider/helpers.ts
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/actions/main-function/guider/index.ts
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/actions/main-function/records/index.ts
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/guider/body/application/students.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/guider/body/application/students/student.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/guider/body/application/toolbar.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/guider/body/application/toolbar/labels.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/guider/body/aside.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/guider/dialogs/student.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/guider/dialogs/student/tabs/contact-events/contact-event.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/guider/dialogs/student/tabs/contact-events/editors/delete-prompt.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/guider/dialogs/student/tabs/contact-events/editors/edit-comment.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/guider/dialogs/student/tabs/contact-events/editors/edit-event.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/guider/dialogs/student/tabs/contact-events/editors/new-event.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/guider/dialogs/student/tabs/state-of-studies.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/guider/dialogs/student/tabs/state-of-studies/ceepos-button.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/guider/dialogs/student/tabs/state-of-studies/ceepos.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/guider/dialogs/student/tabs/study-history.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/guider/dialogs/student/tabs/study-plan.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/reducers/index.ts
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/reducers/main-function/guider/index.ts
  muikku-core-plugins/src/main/resources/META-INF/resources/swagger.yaml
Labels: NEEDS REVIEW

#6719 6694 lokaalien testaus demolla
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/actions/main-function/messages/helpers.ts
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/actions/main-function/messages/index.ts
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-editor/index.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/communicator/body/application/message-view/message.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/coursepicker/body/application/courses/course.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/coursepicker/body/application/toolbar.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/coursepicker/body/aside.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/evaluation/body/application/evaluation-list/evaluation-card.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/evaluation/body/application/evaluation-list/evaluation-sorters.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/evaluation/body/application/evaluation/editors/assignment-editor.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/evaluation/body/application/evaluation/editors/exercise-editor.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/evaluation/body/application/evaluation/evaluation-assessment-assignment.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/evaluation/body/application/evaluation/evaluation-assessment-list.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/evaluation/body/application/evaluation/evaluation-journal-event-list.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/evaluation/dialogs/archive.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/note-book/note-editor.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/guider/dialogs/student/workspaces/workspace.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/index/body/wall-panel.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/organization/dialogs/edit-workspace.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/organization/dialogs/new-workspace.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/profile/body/application/general-information.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/profile/body/application/purchases.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/records/body/application/summary.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/workspace/workspaceManagement/body/management.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/helper-functions/locale.ts
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/locales/translations/en.json
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/locales/translations/fi.json
Labels: IN PROGRESS

#6679 Records api path refactor done
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/actions/main-function/guider/index.ts
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/actions/main-function/hops.ts
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/actions/main-function/records/index.ts
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/actions/main-function/records/summary.ts
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/actions/main-function/records/yo.ts
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/hops_editable.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/hops_readable.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/records/body/application.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/records/body/application/assignments-and-diaries/hooks/useRecordWorkpace.ts
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/records/body/application/hops.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/records/body/application/summary.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/records/body/application/yo.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/records/body/aside.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/records/body/matriculationExaminationWizard/index.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/reducers/index.ts
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/reducers/main-function/guider/index.ts
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/reducers/main-function/hops.ts
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/reducers/main-function/records/index.ts
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/reducers/main-function/records/yo.ts
  muikku-core-plugins/src/main/resources/META-INF/resources/swagger.yaml
Labels: IN PROGRESS, NEEDS REVIEW

#6730 Recipient id removed and replaced with userEntityId
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/communicator/body/application/messages.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/swagger.yaml
Labels: NEEDS REVIEW

#6688 6672 pedagogisen tuen suunnitelma lukutapahtamien lokitus
  muikku-core-plugins-persistence/src/main/java/fi/otavanopisto/muikku/plugins/pedagogy/model/PedagogyFormHistory.java
  muikku-core-plugins-persistence/src/main/java/fi/otavanopisto/muikku/plugins/pedagogy/model/PedagogyFormHistoryType.java
  muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/pedagogy/PedagogyController.java
  muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/pedagogy/dao/PedagogyFormHistoryDAO.java
  muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/pedagogy/rest/PedagogyFormHistoryRestModel.java
  muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/pedagogy/rest/PedagogyRestService.java
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/@types/pedagogy-form.ts
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/discussion/body/application/discussion-thread-reply.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/pedagogical-support-form/context/pedagogy-context.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/pedagogical-support-form/history.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/pedagogical-support-form/steps/basic-information.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/package-lock.json
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/avatar.scss
  updates/1.140/190923_pedagogy_form_history_type.xml
Labels: NEEDS REVIEW

#6731 Removed unused rest model
  muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/communicator/rest/CommunicatorMessageRecipientRESTModel.java
Labels: NEEDS REVIEW

#6732 Oppilaitostiedosta riippuvat arviointimaksut
  muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/guider/GuiderTestsBase.java
  muikku-core-plugins-persistence/src/main/java/fi/otavanopisto/muikku/plugins/ceepos/model/CeeposProductType.java
  muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/assessmentrequest/rest/AssessmentRequestRESTService.java
  muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/ceepos/CeeposController.java
  muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/ceepos/rest/CeeposRESTService.java
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/profile/body/application/purchases.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/locales/translations/en.json
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/locales/translations/fi.json
Labels: NEEDS REVIEW

#6738 Fixes the course description field
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/workspace/workspaceManagement/body/management.tsx
Labels: NEEDS REVIEW

#6640 Log material modifications that leads to answers being removed
  muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/material/HtmlMaterialController.java
  muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/material/rest/HtmlMaterialRESTService.java
  muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/WorkspaceMaterialController.java
  muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/rest/WorkspaceRESTService.java
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/actions/workspaces/material.ts
  muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/workspace/WorkspacePluginMessages_en.properties
Labels: NEEDS REVIEW

#6741 6673 pedagogisen tuen suunnitelman jako oikeuksien muutokset
  muikku-core-plugins-persistence/src/main/java/fi/otavanopisto/muikku/plugins/pedagogy/model/PedagogyForm.java
  muikku-core-plugins-persistence/src/main/java/fi/otavanopisto/muikku/plugins/pedagogy/model/PedagogyFormVisibility.java
  muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/pedagogy/PedagogyController.java
  muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/pedagogy/dao/PedagogyFormDAO.java
  muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/pedagogy/rest/PedagogyFormRestModel.java
  muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/pedagogy/rest/PedagogyFormVisibilityPayload.java
  muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/pedagogy/rest/PedagogyRestService.java
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/@types/pedagogy-form.ts
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/pedagogical-support-form/dialogs/approval.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/pedagogical-support-form/dialogs/visibility.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/pedagogical-support-form/hooks/usePedagogy.ts
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/pedagogical-support-form/pedagogy-toolbar.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/pedagogical-support-form/steps/permissions-and-approval.tsx
  muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/pedagogy/PedagogyPluginMessages_en.properties
  muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/pedagogy/PedagogyPluginMessages_fi.properties
  updates/1.141/290923_pedagogy_form_visibility.xml
Labels: NEEDS REVIEW

#6743 6718 pedagogy form openapi generator rework
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/@types/pedagogy-form.ts
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/actions/main-function/guider/index.ts
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/pedagogical-support-form/helpers.ts
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/pedagogical-support-form/history.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/pedagogical-support-form/hooks/usePedagogy.ts
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/pedagogical-support-form/pedagogy-PDF.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/pedagogical-support-form/steps/basic-information.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/guider/dialogs/student.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/records/body/application.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/reducers/main-function/guider/index.ts
  muikku-core-plugins/src/main/resources/META-INF/resources/swagger.yaml
Labels: NEEDS REVIEW

#6748 Avatar refactore to use img tag
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/avatar.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/avatar.scss
Labels: NEEDS REVIEW

#6737 Notes api path rework done
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/@types/notes.ts
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/notes/helpers/filters.ts
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/notes/hooks/useNotesItems.ts
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/notes/notes-item-edit.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/notes/notes-item-list-item.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/notes/notes-item-list.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/notes/notes-item-new.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/notes/notes.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/index/body/wall-panel.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/index/body/wall/note.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/hooks/useNotes.ts
  muikku-core-plugins/src/main/resources/META-INF/resources/swagger.yaml
Labels: NEEDS REVIEW

#6675 Hops paths refactored to use newly generated api
  muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/hops/rest/HopsRestService.java
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/@types/shared.ts
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/actions/main-function/guider/index.ts
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/carousel/hooks/use-course-carousel.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/carousel/workspace-description-dialog.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/hops-compulsory-education-wizard/context/follow-up-context.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/hops-compulsory-education-wizard/hooks/useStudentStudyHours.ts
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/hops-compulsory-education-wizard/hooks/useSuggestedList.ts
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/hops-compulsory-education-wizard/hops-course-list.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/hops-compulsory-education-wizard/hops-course-table.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/hops-compulsory-education-wizard/hops-follow-up-goals.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/hops-compulsory-education-wizard/hops-history.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/hops-compulsory-education-wizard/hops-steps/hops-studies-planning.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/hops-compulsory-education-wizard/hops-suggested-list.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/hops-compulsory-education-wizard/index.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/helper-functions/shared.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/hooks/useNextCourseSuggestions.ts
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/hooks/useStudentActivity.ts
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/hooks/useStudentAlternativeOptions.ts
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/hooks/useStudentChoices.ts
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/hooks/useSupervisorOptionalSuggestion.ts
  muikku-core-plugins/src/main/resources/META-INF/resources/swagger.yaml
Labels: NEEDS REVIEW

#6739 6735 activity logs openapi generator rework
  muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/activitylog/rest/ActivityLogRESTService.java
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/actions/main-function/guider/index.ts
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/actions/main-function/records/summary.ts
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/api/api.ts
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/graph/main-chart.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/guider/dialogs/student/workspaces/workspace/workspace-chart.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/reducers/main-function/guider/index.ts
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/reducers/main-function/records/summary.ts
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/reducers/workspaces/index.ts
  muikku-core-plugins/src/main/resources/META-INF/resources/swagger.yaml
  muikku-core/src/main/java/fi/otavanopisto/muikku/rest/ISO8601UTCTimestamp.java
Labels: NEEDS REVIEW

#6774 Fix for guider crashing with some students
  muikku-rest/src/main/java/fi/otavanopisto/muikku/rest/user/UserRESTService.java
Labels: NEEDS REVIEW

#6780 Fixed issue where client is left hanging and garbage collected
  muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/feed/FeedSynchronizer.java
Labels: NEEDS REVIEW

#6781 Removed deprecated context-param
  muikku/src/main/webapp/WEB-INF/web.xml
Labels: NEEDS REVIEW

#6803 6769 sekalaisia lokaalipaivityksen korjauksia
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/evaluation/body/application/evaluation/evaluation-journal-event-list.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/guider/dialogs/student/tabs/contact-events/contact-event.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/workspace/workspaceHelp/help/index.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/workspace/workspaceJournal/body/application/editors/workspace-journal-comment-editor.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/workspace/workspaceJournal/body/application/workspace-journal-comment-list-item.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/workspace/workspaceJournal/body/application/workspace-journal-comment-list.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/locales/translations/en.json
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/locales/translations/fi.json
Labels: NEEDS REVIEW

#6854 6704 pedagogy form localization
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/pedagogical-support-form/dialogs/approval.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/pedagogical-support-form/dialogs/save-with-extra-details.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/pedagogical-support-form/dialogs/warning.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/pedagogical-support-form/helpers.ts
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/pedagogical-support-form/history.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/pedagogical-support-form/implemented-actions.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/pedagogical-support-form/index.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/pedagogical-support-form/opinions-list.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/pedagogical-support-form/pedagogy-PDF.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/pedagogical-support-form/pedagogy-form-wizard-footer.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/pedagogical-support-form/pedagogy-toolbar.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/pedagogical-support-form/steps/basic-information.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/pedagogical-support-form/steps/document-information.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/pedagogical-support-form/steps/implemented-support-actions.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/pedagogical-support-form/steps/monitoring-and-evaluation.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/pedagogical-support-form/steps/need-of-support-information.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/pedagogical-support-form/steps/permissions-and-approval.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/pedagogical-support-form/workspace-select.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/guider/dialogs/label-update.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/guider/dialogs/student.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/records/body/application.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/records/body/application/summary.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/locales/translations/en.json
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/locales/translations/fi.json
Labels: IN PROGRESS
