Repository otavanopisto/muikku, pull requests merged in 2024-05, with the labels that each got.

#7056 Material permission tuning
  muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/rest/WorkspaceRESTService.java
Labels: NEEDS REVIEW

#7035 7034 opinnot nakyman korjauksia
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/records/body/application.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/records/body/application/matriculation-subjects/matriculation-subjects-list.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/records/body/application/summary.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/locales/translations/en.json
Labels: NEEDS REVIEW

#7025 6833 wcag 1.1.1, 2.1.1 ja 4.1.2. suoritukset valilehdella on useita saavutettavuusongelmia
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/records-history/activity-indicator.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/records-history/records-group-item.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/records-history/records-group.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/locales/translations/en.json
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/locales/translations/fi.json
Labels: IN PROGRESS

#7026 Tabs have now better keyboard support with arrow left and right chang…
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/tabs.tsx
Labels: NEEDS REVIEW

#7029 6823 wcag 1.3.1, 2.1.1, 4.1.2 keskustelualueen viesteja ei saa auki nappaimistolla, alue on epaselva ruudunlukijalla
  muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/discussions/DiscussionTestsBase.java
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/discussion/body/application/discussion-current-thread.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/discussion/body/application/discussion-subscriptions.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/discussion/body/application/discussion-threads.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/discussion/body/application/threads/area.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/discussion/body/application/threads/threads.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/avatar.tsx
Labels: NEEDS REVIEW

#7059 7057 new ckeditor style boxes
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/ckplugins/styles/workspace-material-styles.js
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-loader/base/index.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-loader/content.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/material-page.scss
Labels: NEEDS REVIEW

#7030 6829 wcag 1.3.1, 2.1.1 ja 4.1.2. aktiiviset tehtavat alueella on useita saavutettavuusongelmia
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/notes/notes-item-list-filters-chip.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/notes/notes-item-list-item.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/notes/notes-item-list.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/notes/notes.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/locales/translations/en.json
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/locales/translations/fi.json
Labels: NEEDS REVIEW

#7049 7048-changes:
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/evaluation/body/application/evaluation/slide-drawer.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/dialog.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/environment-dialog.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/portal.tsx
Labels: HOLD_MERGE, NEEDS REVIEW

#7062 6860 wcag 2.1.1 materiaaleissa liikkuminen ei onnistu nappaimistolla
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-loader/index.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-loader/title.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/content-panel.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/link.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/toc.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/workspace/workspaceHelp/content.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/workspace/workspaceHelp/help/help-material-page.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/workspace/workspaceHelp/help/index.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/workspace/workspaceMaterials/content.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/workspace/workspaceMaterials/materials/index.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/workspace/workspaceMaterials/materials/material.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/locales/translations/en.json
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/locales/translations/fi.json
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/buttons.scss
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/material-page.scss
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/util/base.scss
Labels: NEEDS REVIEW

#6578 Java 17 tests testing
  .github/workflows/accessibilityChecks.yml
  .github/workflows/announcerTest.yml
  .github/workflows/communicatorTest.yml
  .github/workflows/courseAnnouncerTest.yml
  .github/workflows/courseJournalTest.yml
  .github/workflows/courseManagementTest.yml
  .github/workflows/courseMaterialsManagementTest.yml
  .github/workflows/courseMaterialsTest.yml
  .github/workflows/courseTests.yml
  .github/workflows/courseUsersTest.yml
  .github/workflows/coursepickerTests.yml
  .github/workflows/deploySnapshot.yml
  .github/workflows/discussionsTest.yml
  .github/workflows/flagsTest.yml
  .github/workflows/guiderTest.yml
  .github/workflows/indexPageTest.yml
  .github/workflows/newevaluationTest.yml
  .github/workflows/releaseOrDeploy.yml
  .github/workflows/restTest.yml
  .github/workflows/torTest.yml
  .github/workflows/userTest.yml
  muikku-atests/pom.xml
  pom.xml
Labels: NEEDS REVIEW

#7055 7033 signup message
  muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/course/management/CourseManagementTestsBase.java
  muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/coursepicker/CoursePickerRESTService.java
  muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/guider/GuiderRESTService.java
  muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/rest/WorkspaceRESTService.java
  muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/rest/WorkspaceSignupGroupsRESTService.java
  muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/rest/model/WorkspaceSettingsRestModel.java
  muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/rest/model/WorkspaceSignupGroupRestModel.java
  muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/rest/model/WorkspaceSignupMessageRestModel.java
  muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/rest/model/WorkspaceSignupUserGroup.java
  muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/rest/model/WorkspaceSignupUserGroupListRestModel.java
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/actions/workspaces/index.ts
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/coursepicker/dialogs/workspace-signup.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/workspace/workspaceManagement/body/management-additional-info.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/workspace/workspaceManagement/body/management-basic-info.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/workspace/workspaceManagement/body/management-chat-settings.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/workspace/workspaceManagement/body/management-image.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/workspace/workspaceManagement/body/management-license.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/workspace/workspaceManagement/body/management-producers.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/workspace/workspaceManagement/body/management-schedule.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/workspace/workspaceManagement/body/management-signup-groups.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/workspace/workspaceManagement/body/management-signup-message.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/workspace/workspaceManagement/body/management-visibility.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/workspace/workspaceManagement/body/management.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/containers/workspace.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/locales/translations/en.json
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/locales/translations/fi.json
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/reducers/workspaces/index.ts
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/buttons.scss
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/dialog.scss
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/form.scss
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/util/base.scss
  muikku-core-plugins/src/main/resources/META-INF/resources/swagger.yaml
  muikku-core/pom.xml
  muikku-core/src/main/java/fi/otavanopisto/muikku/schooldata/WorkspaceController.java
  muikku-core/src/main/java/fi/otavanopisto/muikku/schooldata/WorkspaceSignupGroupController.java
  muikku-core/src/main/java/fi/otavanopisto/muikku/schooldata/WorkspaceSignupMessageController.java
  muikku-persistence/src/main/java/fi/otavanopisto/muikku/dao/workspace/WorkspaceSignupMessageDAO.java
  muikku-persistence/src/main/java/fi/otavanopisto/muikku/model/workspace/WorkspaceSignupMessage.java
  muikku-rest/src/main/resources/fi/otavanopisto/muikku/rest/workspace/WorkspaceRestMessages_en.properties
  muikku-rest/src/main/resources/fi/otavanopisto/muikku/rest/workspace/WorkspaceRestMessages_fi.properties
  updates/1.149/240416_workspacesignupmessage.xml
Labels: NEEDS REVIEW

#7022 6865 wcag 1.3.1, 2.1.1 ja 2.5.7 raahaustehtavat eivat ole saavutettavia nappaimisto ja ruudunlukijakayttajille
  muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/course/materials/CourseMaterialsPageTestsBase.java
  muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/guider/GuiderTestsBase.java
  muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/newevaluation/NewEvaluationTestsBase.java
  muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/tor/ToRTestsBase.java
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-loader/fields/audio-field/index.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-loader/fields/better-math-field/field.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-loader/fields/connect-field.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-loader/fields/file-field/index.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-loader/fields/journal-field.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-loader/fields/math-field.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-loader/fields/memo-field.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-loader/fields/multiselect-field.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-loader/fields/organizer-field.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-loader/fields/select-field.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-loader/fields/sorter-field.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-loader/fields/text-field.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/locales/translations/en.json
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/locales/translations/fi.json
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/base/colors.scss
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/audiofield.scss
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/checkboxfield.scss
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/connectfield.scss
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/file-uploader.scss
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/filefield.scss
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/journalfield.scss
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/material-page.scss
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/mathfield.scss
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/memofield.scss
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/organizerfield.scss
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/radiobuttonfield.scss
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/selectfield.scss
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/sorterfield.scss
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/textfield.scss
Labels: NEEDS REVIEW

#7058 6999 word limit
  muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/material/fieldmeta/MemoFieldMeta.java
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/ckplugins/muikku-memofield/lang/en.js
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/ckplugins/muikku-memofield/lang/fi.js
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/ckplugins/muikku-memofield/plugin.js
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-loader/fields/memo-field.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/ckeditor.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/locales/translations/en.json
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/locales/translations/fi.json
Labels: NEEDS REVIEW

#7065 Mathjax rollback from 2.7.9 to 2.7.7
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/ckplugins/muikku-mathjax/plugin.js
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/lib/mathjax.ts
Labels: NEEDS REVIEW

#7068 7067 workspace signup message after testing changes
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/workspace/workspaceManagement/body/management-signup-groups.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/workspace/workspaceManagement/body/management-signup-message.tsx
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/locales/translations/en.json
  muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/locales/translations/fi.json
Labels: NEEDS REVIEW

#7071 * Openfire-rest-client gone bye bye
  muikku-openfire-rest-client/.gitignore
  muikku-openfire-rest-client/LICENSE.txt
  muikku-openfire-rest-client/README.md
  muikku-openfire-rest-client/pom.xml
  muikku-openfire-rest-client/src/main/java/fi/otavanopisto/muikku/openfire/rest/client/RestApiClient.java
  muikku-openfire-rest-client/src/main/java/fi/otavanopisto/muikku/openfire/rest/client/RestClient.java
  muikku-openfire-rest-client/src/main/java/fi/otavanopisto/muikku/openfire/rest/client/entity/AuthenticationMode.java
  muikku-openfire-rest-client/src/main/java/fi/otavanopisto/muikku/openfire/rest/client/entity/AuthenticationToken.java
  muikku-openfire-rest-client/src/main/java/fi/otavanopisto/muikku/openfire/rest/client/entity/GroupEntities.java
  muikku-openfire-rest-client/src/main/java/fi/otavanopisto/muikku/openfire/rest/client/entity/GroupEntity.java
  muikku-openfire-rest-client/src/main/java/fi/otavanopisto/muikku/openfire/rest/client/entity/MUCRoomEntities.java
  muikku-openfire-rest-client/src/main/java/fi/otavanopisto/muikku/openfire/rest/client/entity/MUCRoomEntity.java
  muikku-openfire-rest-client/src/main/java/fi/otavanopisto/muikku/openfire/rest/client/entity/ParticipantEntities.java
  muikku-openfire-rest-client/src/main/java/fi/otavanopisto/muikku/openfire/rest/client/entity/ParticipantEntity.java
  muikku-openfire-rest-client/src/main/java/fi/otavanopisto/muikku/openfire/rest/client/entity/RosterEntities.java
  muikku-openfire-rest-client/src/main/java/fi/otavanopisto/muikku/openfire/rest/client/entity/RosterItemEntity.java
  muikku-openfire-rest-client/src/main/java/fi/otavanopisto/muikku/openfire/rest/client/entity/SessionEntities.java
  muikku-openfire-rest-client/src/main/java/fi/otavanopisto/muikku/openfire/rest/client/entity/SessionEntity.java
  muikku-openfire-rest-client/src/main/java/fi/otavanopisto/muikku/openfire/rest/client/entity/SystemProperties.java
  muikku-openfire-rest-client/src/main/java/fi/otavanopisto/muikku/openfire/rest/client/entity/SystemProperty.java
  muikku-openfire-rest-client/src/main/java/fi/otavanopisto/muikku/openfire/rest/client/entity/UserEntities.java
  muikku-openfire-rest-client/src/main/java/fi/otavanopisto/muikku/openfire/rest/client/entity/UserEntity.java
  muikku-openfire-rest-client/src/main/java/fi/otavanopisto/muikku/openfire/rest/client/entity/UserGroupsEntity.java
  muikku-openfire-rest-client/src/main/java/fi/otavanopisto/muikku/openfire/rest/client/entity/UserProperty.java
  muikku-openfire-rest-client/src/main/java/fi/otavanopisto/muikku/openfire/rest/client/exception/ErrorResponse.java
  pom.xml
Labels: NEEDS REVIEW
